spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.255.129:3307/iotmall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: iotmall-product
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.255.129
    port: 6379


mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      #逻辑删除用1，不删除用0
server:
  port: 10000
logging:
  level:
    com.liang.iotmall: error


#alibaba:
#  cloud:
#    oss:
#      sts:
#        access-key: LTAI5tShHPTsH6ZZvvV9TAqN
#        secret-key: fq4dr5UFmj7jWKGq8rA61dkq6ttR4S
#      endpoint: oss-cn-beijing.aliyuncs.com

