server:
  port: 40000

spring:
  application:
    name: iotmall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#    sentinel:
#      transport:
#        #配置sentinel dashboard地址
#        dashboard: 192.168.2.131:8080
  redis:
    port: 6379
    host: 192.168.255.129

#开启feign对sentinel的支持
#feign:
#  sentinel:
#    enabled: true
  session:
    store-type: redis

#配置线程池
iotmall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

##暴露所有端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'


