spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      secret-key: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      oss:
        endpoint: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        bucket: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
      sms:
        host: XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        path: /sms/smsSend?
        template_id: TPL_0000
        appcode: XXXXXXXXXXXXXXXXXXXXXXXXXXXX

  application:
    name: iotmall-third-party
server:
  port: 30000
